/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface WcuButton {
        "disabled": boolean;
        "height": string;
        "loading": boolean;
        "size": 'small'|'medium'|'large';
        "text": string;
        "type": 'primary'|'danger'|'success'|'info'|'warning'|'text';
        "width": string;
    }
    interface WcuIcon {
        /**
          * 传入的class名称
         */
        "classNames": string;
        /**
          * 图标颜色
         */
        "color": string;
        /**
          * 旋转的角度
         */
        "rotate": number;
        /**
          * icon 尺寸 默认 20
         */
        "size": number | string;
        /**
          * 是否自动旋转
         */
        "spin": boolean;
        /**
          * styles 传入的css样式
         */
        "styles": object;
    }
    interface WcuImage {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLWcuButtonElement extends Components.WcuButton, HTMLStencilElement {
    }
    var HTMLWcuButtonElement: {
        prototype: HTMLWcuButtonElement;
        new (): HTMLWcuButtonElement;
    };
    interface HTMLWcuIconElement extends Components.WcuIcon, HTMLStencilElement {
    }
    var HTMLWcuIconElement: {
        prototype: HTMLWcuIconElement;
        new (): HTMLWcuIconElement;
    };
    interface HTMLWcuImageElement extends Components.WcuImage, HTMLStencilElement {
    }
    var HTMLWcuImageElement: {
        prototype: HTMLWcuImageElement;
        new (): HTMLWcuImageElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "wcu-button": HTMLWcuButtonElement;
        "wcu-icon": HTMLWcuIconElement;
        "wcu-image": HTMLWcuImageElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface WcuButton {
        "disabled"?: boolean;
        "height"?: string;
        "loading"?: boolean;
        "size"?: 'small'|'medium'|'large';
        "text"?: string;
        "type"?: 'primary'|'danger'|'success'|'info'|'warning'|'text';
        "width"?: string;
    }
    interface WcuIcon {
        /**
          * 传入的class名称
         */
        "classNames"?: string;
        /**
          * 图标颜色
         */
        "color"?: string;
        /**
          * 旋转的角度
         */
        "rotate"?: number;
        /**
          * icon 尺寸 默认 20
         */
        "size"?: number | string;
        /**
          * 是否自动旋转
         */
        "spin"?: boolean;
        /**
          * styles 传入的css样式
         */
        "styles"?: object;
    }
    interface WcuImage {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "wcu-button": WcuButton;
        "wcu-icon": WcuIcon;
        "wcu-image": WcuImage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "wcu-button": LocalJSX.WcuButton & JSXBase.HTMLAttributes<HTMLWcuButtonElement>;
            "wcu-icon": LocalJSX.WcuIcon & JSXBase.HTMLAttributes<HTMLWcuIconElement>;
            "wcu-image": LocalJSX.WcuImage & JSXBase.HTMLAttributes<HTMLWcuImageElement>;
        }
    }
}
